In [7]:
import pandas as pd

In [8]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})


In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
bow = CountVectorizer()

In [11]:
data['text']

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [12]:
X = bow.fit_transform(data['text'])

In [13]:
print("Vocabulary ", bow.vocabulary_)

Vocabulary  {'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}


In [14]:
print("Feature matrix:\n", X.toarray())

Feature matrix:
 [[0 1 0 1 1]
 [0 2 0 0 1]
 [1 0 1 1 0]
 [1 1 1 0 0]]


## Using Dummies


In [15]:
ohe = pd.get_dummies(data['text'])
print(ohe)

   cricket give comment  cricket watch cricket  people give comment  \
0                 False                  False                False   
1                 False                   True                False   
2                 False                  False                 True   
3                  True                  False                False   

   people watch cricket  
0                  True  
1                 False  
2                 False  
3                 False  


In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
bigram = CountVectorizer(ngram_range=(2,3))


In [18]:
Y = bigram.fit_transform(data['text'])

In [26]:
bigram.vocabulary_

{'people watch': 7,
 'watch cricket': 9,
 'people watch cricket': 8,
 'cricket watch': 2,
 'cricket watch cricket': 3,
 'people give': 5,
 'give comment': 4,
 'people give comment': 6,
 'cricket give': 0,
 'cricket give comment': 1}

In [20]:
import torch

In [27]:
import torch

# Categories represented as integers
categories = torch.tensor([0, 1, 2, 0, 2])  # e.g., 0: Red, 1: Green, 2: Blue

# Number of unique categories
num_categories = 3  # Adjust this based on your dataset

# One-hot encoding
one_hot_encoded = torch.nn.functional.one_hot(categories, num_classes=num_categories)

print(one_hot_encoded)


tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 0, 1]])


In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "the cat and the dog played together"
]
vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(corpus)
feature_names = vectorizer.get_feature_names_out()
tfidf_dense = tfidf.todense()
print("TF-IDF Matrix:")
print(tfidf_dense)

print("\nFeature Names:")
print(feature_names)


TF-IDF Matrix:
[[0.         0.37420726 0.         0.         0.49203758 0.37420726
  0.         0.37420726 0.58121064 0.        ]
 [0.         0.         0.37420726 0.49203758 0.         0.37420726
  0.         0.37420726 0.58121064 0.        ]
 [0.42439575 0.32276391 0.32276391 0.         0.         0.
  0.42439575 0.         0.50130994 0.42439575]]

Feature Names:
['and' 'cat' 'dog' 'log' 'mat' 'on' 'played' 'sat' 'the' 'together']


In [1]:
!pip uninstall numpy -y
!pip install numpy==1.26.4
!pip uninstall gensim -y
!pip install gensim==4.3.3


from gensim.models import Word2Vec, KeyedVectors

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Found existing installation: gensim 4.3.3
Uninstalling gensim-4.3.3:
  Successfully uninstalled gensim-4.3.3
  Using cached gensim-4.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.1 kB)
Using cached gensim-4.3.3-cp311-cp311-macosx_11_0_arm64.whl (24.0 MB)


In [2]:
import gensim.downloader as api

In [5]:
model = api.load("glove-wiki-gigaword-100")  # Smaller GloVe model


[==================================================] 100.0% 128.1/128.1MB downloaded


In [10]:
import gensim.downloader as api
print(api.BASE_DIR)


/Users/harishk/gensim-data


In [7]:
len(model["sunny"])


100

In [14]:
model['india']

array([-0.95967  ,  0.30795  ,  0.90052  ,  1.0364   ,  0.0034906,
       -0.80758  , -1.139    ,  0.81109  , -0.67857  ,  0.52609  ,
       -0.072252 , -0.75613  ,  0.52847  ,  1.0927   , -0.51895  ,
       -0.21335  ,  0.18184  ,  0.40038  , -0.6547   ,  0.34626  ,
        0.92248  , -0.25001  ,  1.1779   ,  0.61006  ,  0.029763 ,
        0.4378   ,  0.53647  ,  0.68827  ,  0.14582  , -0.27446  ,
       -0.50289  ,  1.0366   , -0.29851  , -0.32927  ,  0.24944  ,
       -0.33779  ,  0.0083236, -0.21373  , -0.45898  , -0.23441  ,
       -1.2958   ,  0.74799  ,  0.78192  , -0.75644  ,  0.84375  ,
       -0.51725  ,  1.0952   ,  0.51768  ,  0.27906  , -0.033519 ,
       -0.1573   ,  0.7396   ,  0.39775  ,  1.132    , -0.69279  ,
       -2.0093   , -1.1731   , -0.14204  ,  1.5658   , -0.097956 ,
       -0.071165 , -0.18906  ,  0.037441 ,  0.48037  ,  0.29248  ,
        0.9216   ,  0.33285  ,  0.30963  ,  1.1272   ,  0.19965  ,
        0.47058  ,  0.019022 , -0.27432  , -0.49782  , -0.2944

In [26]:
model.most_similar('india')

[('pakistan', 0.8370324373245239),
 ('indian', 0.780203104019165),
 ('delhi', 0.7712194323539734),
 ('bangladesh', 0.7661641240119934),
 ('lanka', 0.7639288306236267),
 ('sri', 0.7506584525108337),
 ('australia', 0.704209566116333),
 ('malaysia', 0.6796303391456604),
 ('nepal', 0.6761943697929382),
 ('thailand', 0.6671633124351501)]

In [27]:
model.similarity('india','america')

0.46522087

In [37]:
model.doesnt_match(["Me","You","Us"])


ValueError: cannot select a word from an empty list

In [31]:
vec=model['king'] - model['man'] + model['woman']
model.most_similar(vec)


[('king', 0.8551837205886841),
 ('queen', 0.7834413647651672),
 ('monarch', 0.6933802366256714),
 ('throne', 0.6833109259605408),
 ('daughter', 0.680908203125),
 ('prince', 0.6713142991065979),
 ('princess', 0.664408266544342),
 ('mother', 0.6579325199127197),
 ('elizabeth', 0.6563301086425781),
 ('father', 0.6392418742179871)]